import type { SubagentDefinition } from './SubagentDefinition';

export const DEFAULT_SUBAGENTS: SubagentDefinition[] = [
  {
    role: 'search',
    displayName: 'Search',
    promptFile: 'subagents/search.md',
    preferredAgentIds: ['antigravity', 'grok', 'codex', 'claude', 'copilot', 'aider', 'custom'],
    applicableModes: ['ask', 'edit', 'debug', 'test', 'plan', 'research', 'brainstorm', 'review'],
    capabilities: ['project_search'],
    canRunInParallel: true,
  },
  {
    role: 'planner',
    displayName: 'Planner',
    promptFile: 'subagents/planner.md',
    preferredAgentIds: ['codex', 'claude', 'grok', 'antigravity', 'copilot', 'aider', 'custom'],
    applicableModes: ['edit', 'debug', 'test', 'plan', 'brainstorm', 'review'],
    capabilities: ['implementation_planning'],
    dependsOn: ['search'],
  },
  {
    role: 'coder',
    displayName: 'Coder',
    promptFile: 'subagents/coder.md',
    preferredAgentIds: ['codex', 'claude', 'grok', 'antigravity', 'copilot', 'aider', 'custom'],
    applicableModes: ['edit'],
    capabilities: ['implementation'],
    dependsOn: ['planner'],
  },
  {
    role: 'debugger',
    displayName: 'Debugger',
    promptFile: 'subagents/debugger.md',
    preferredAgentIds: ['codex', 'claude', 'grok', 'antigravity', 'copilot', 'aider', 'custom'],
    applicableModes: ['debug'],
    capabilities: ['root_cause_analysis'],
    dependsOn: ['search'],
  },
  {
    role: 'tester',
    displayName: 'Test Analyst',
    promptFile: 'subagents/tester.md',
    preferredAgentIds: ['codex', 'claude', 'grok', 'antigravity', 'copilot', 'aider', 'custom'],
    applicableModes: ['edit', 'test', 'debug'],
    capabilities: ['test_design'],
    dependsOn: ['search'],
  },
  {
    role: 'reviewer',
    displayName: 'Reviewer',
    promptFile: 'subagents/reviewer.md',
    preferredAgentIds: ['codex', 'claude', 'grok', 'antigravity', 'copilot', 'aider', 'custom'],
    applicableModes: ['edit', 'review', 'test', 'debug'],
    capabilities: ['code_review'],
  },
  {
    role: 'security',
    displayName: 'Security',
    promptFile: 'subagents/security.md',
    preferredAgentIds: ['codex', 'claude', 'grok', 'antigravity', 'copilot', 'aider', 'custom'],
    applicableModes: ['edit', 'review', 'debug'],
    capabilities: ['security_review'],
    dependsOn: ['search'],
  },
  {
    role: 'docs',
    displayName: 'Docs',
    promptFile: 'subagents/docs.md',
    preferredAgentIds: ['codex', 'claude', 'grok', 'antigravity', 'copilot', 'aider', 'custom'],
    applicableModes: ['ask', 'plan', 'brainstorm', 'review'],
    capabilities: ['documentation_review'],
    dependsOn: ['search'],
  },
  {
    role: 'product',
    displayName: 'Product',
    promptFile: 'subagents/product.md',
    preferredAgentIds: ['codex', 'claude', 'grok', 'antigravity', 'copilot', 'aider', 'custom'],
    applicableModes: ['plan', 'brainstorm', 'ask', 'edit'],
    capabilities: ['product_requirements'],
    canRunInParallel: true,
  },
  {
    role: 'research',
    displayName: 'Research',
    promptFile: 'subagents/research.md',
    preferredAgentIds: ['antigravity', 'grok', 'codex', 'claude', 'copilot', 'aider', 'custom'],
    applicableModes: ['ask', 'research', 'plan', 'edit'],
    capabilities: ['research'],
    canRunInParallel: true,
  },
];
