import { useEffect, useRef, useState, useId } from 'react';
import { CodeBlock } from './CodeBlock';

interface Props {
  diagram: string;
}

export function MermaidBlock({ diagram }: Props) {
  const rawId = useId().replace(/:/g, '');  // mermaid id cannot contain colons
  const id = `mermaid-${rawId}`;
  const [svg, setSvg] = useState<string | null>(null);
  const [error, setError] = useState(false);
  const mountedRef = useRef(true);

  useEffect(() => {
    mountedRef.current = true;
    let cancelled = false;

    import('mermaid').then(({ default: mermaid }) => {
      if (cancelled || !mountedRef.current) return;

      mermaid.initialize({
        startOnLoad: false,
        theme: 'dark',
        securityLevel: 'strict',
        fontFamily: 'var(--vscode-font-family, sans-serif)',
      });

      mermaid.render(id, diagram)
        .then(({ svg: renderedSvg }) => {
          if (!cancelled && mountedRef.current) {
            setSvg(renderedSvg);
          }
        })
        .catch(() => {
          if (!cancelled && mountedRef.current) {
            setError(true);
          }
        });
    }).catch(() => {
      if (!cancelled && mountedRef.current) {
        setError(true);
      }
    });

    return () => {
      cancelled = true;
      mountedRef.current = false;
    };
  }, [diagram, id]);

  if (error) {
    return <CodeBlock language="mermaid">{diagram}</CodeBlock>;
  }

  if (svg === null) {
    return (
      <div className="nx-mermaid-loading" aria-label="Rendering diagram">
        <span className="nx-streaming-spinner" aria-hidden="true" />
        <span>Rendering diagram…</span>
      </div>
    );
  }

  return (
    <div
      className="nx-mermaid-block"
      // Safe: SVG is generated by mermaid from the diagram source, not from user HTML
      // eslint-disable-next-line react/no-danger
      dangerouslySetInnerHTML={{ __html: svg }}
      aria-label="Mermaid diagram"
    />
  );
}
